{{- if and .Values.postgres.enabled .Values.postgres.operatorManaged -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "eneo.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eneo.labels" . | nindent 4 }}
spec:
  imageName: {{ .Values.postgres.imageName }}
  instances: {{ .Values.postgres.instances }}
  enablePDB: {{ if eq (int .Values.postgres.instances) 1 }}false{{ else }}true{{ end }}
  bootstrap:
    {{- if .Values.copyFrom.enabled }}
    pg_basebackup:
      source: {{ include "eneo.sourceFullname" . }}-postgres
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
    {{- else }}
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
    {{- end }}
  storage:
    size: {{ .Values.postgres.storage.size }}
  {{- if .Values.postgres.resources }}
  resources:
    {{- toYaml .Values.postgres.resources | nindent 4 }}
  {{- end }}
  {{- if .Values.postgres.parameters }}
  postgresql:
    parameters:
      {{- toYaml .Values.postgres.parameters | nindent 6 }}
  {{- end }}
  {{- if not (or .Values.global.testCluster .Values.testEnvironment) }}
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: {{ include "eneo.fullname" . }}-backup-store
  {{- end }}
  {{- if .Values.copyFrom.enabled }}
  externalClusters:
  - name: {{ include "eneo.sourceFullname" . }}-postgres
    connectionParameters:
      host: {{ include "eneo.sourceFullname" . }}-postgres-rw.{{ .Release.Namespace }}.svc
      user: streaming_replica
      sslmode: verify-full
    sslKey:
      name: {{ include "eneo.sourceFullname" . }}-postgres-replication
      key: tls.key
    sslCert:
      name: {{ include "eneo.sourceFullname" . }}-postgres-replication
      key: tls.crt
    sslRootCert:
      name: {{ include "eneo.sourceFullname" . }}-postgres-ca
      key: ca.crt
  {{- end }}
{{- end }}