{{- if .Values.mariadb.enabled -}}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "hej.fullname" . }}-mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hej.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  replicas: 1
  image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
  imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
  port: 3306
  database: {{ .Values.mariadb.auth.database | quote }}
  username: {{ .Values.mariadb.auth.username | quote }}
  passwordSecretKeyRef:
    name: {{ include "hej.fullname" . }}-secrets
    key: MARIADB_PASSWORD
  rootPasswordSecretKeyRef:
    name: {{ include "hej.fullname" . }}-secrets
    key: MARIADB_ROOT_PASSWORD
  storage:
    size: {{ .Values.mariadb.persistence.size }}
    {{- if .Values.mariadb.persistence.storageClass }}
    storageClassName: {{ .Values.mariadb.persistence.storageClass | quote }}
    {{- end }}
  myCnf: |
    [mariadb]
    bind-address=0.0.0.0
    max-allowed-packet=128M
    innodb-log-file-size=64M
  resources:
    {{- toYaml .Values.mariadb.resources | nindent 4 }}
{{- end }}
