apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hej.fullname" . }}-overview-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hej.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ printf "%s-overview" (include "hej.fullname" .) | quote }}]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hej.fullname" . }}-overview-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hej.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hej.fullname" . }}-overview-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.overview.serviceAccountName }}
    namespace: {{ .Values.overview.serviceAccountNamespace }}