apiVersion: v1
kind: Service
metadata:
  name: {{ include "switchyard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "switchyard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if .Values.auth.enabled }}8080{{ else }}4000{{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "switchyard.selectorLabels" . | nindent 4 }}
