apiVersion: v2
name: eneo
description: A Helm chart for eneo application
type: application
version: 1.0.96
appVersion: "1.8.0-rc.1"
keywords:
  - eneo
  - ai
  - backend
  - frontend
maintainers:
  - name: GDM
