apiVersion: v2
name: eneo
description: A Helm chart for eneo application
type: application
version: 1.0.132
appVersion: "2.0.1-feature-refactor-flows-flowai"
keywords:
  - eneo
  - ai
  - backend
  - frontend
maintainers:
  - name: GDM
