#!/usr/bin/env bash
# Fails if any Helm hook template references a resource that is NOT itself a
# hook (or generated by an operator at runtime). This is the bug class that
# broke fresh eneo installs in 1.0.151–1.0.183: the pre-install migrate job
# mounted the eneo-files ConfigMap, but hooks run BEFORE regular manifests,
# so the mount 404'd on any fresh install.
#
# Usage: ./scripts/check-hook-deps.sh [chart-dir]...
# Exits non-zero on the first chart with a violation.

set -euo pipefail

charts=("$@")
if [[ ${#charts[@]} -eq 0 ]]; then
  charts=(charts/*)
fi

fail=0

for chart in "${charts[@]}"; do
  [[ -d "$chart/templates" ]] || continue
  name=$(basename "$chart")

  # Render the chart with minimal values; we only need structure, not validity.
  # Charts with required values get a synthetic domain so validation runs.
  rendered=$(mktemp)
  if ! helm template "$chart" --set global.domain=hookcheck.invalid >/dev/null 2>"$rendered.err"; then
    echo "SKIP $name: helm template failed: $(head -1 "$rendered.err")"
    rm -f "$rendered" "$rendered.err"
    continue
  fi
  rm -f "$rendered.err"

  # Collect hook resources: (kind, fullname) for every doc with a hook annotation.
  # Collect regular resources: (kind, fullname) for every doc without one.
  hook_docs=$(mktemp); plain_docs=$(mktemp)
  python3 - "$rendered" "$hook_docs" "$plain_docs" <<'EOF'
import re, sys

rendered, hook_out, plain_out = sys.argv[1:4]
text = open(rendered).read()
for doc in text.split("\n---\n"):
    if not doc.strip():
        continue
    kind = re.search(r"^kind: (\w+)", doc, re.M)
    name = re.search(r"^  name: (\S+)", doc, re.M)
    if not kind or not name:
        continue
    # Skip subPath entries etc. — only top-level metadata name matters
    ident = f"{kind.group(1)}/{name.group(1)}"
    if re.search(r"helm\.sh/hook", doc):
        open(hook_out, "a").write(ident + "\n")
    else:
        open(plain_out, "a").write(ident + "\n")
EOF

  # For each hook doc, extract every resource name it references via
  # secretKeyRef / configMapRef / secretRef / configMap: / claimName, and
  # flag references that resolve to a plain (non-hook) manifest resource.
  violations=$(python3 - "$rendered" "$hook_docs" "$plain_docs" <<'EOF'
import re, sys

rendered, hook_docs_f, plain_docs_f = sys.argv[1:4]
text = open(rendered).read()

plain = set(open(plain_docs_f).read().split())
hooks = set(open(hook_docs_f).read().split())

# Names generated by operators at runtime, not by the chart — always allowed.
OPERATOR_GENERATED = re.compile(r"-(postgres-app|-superuser|-rw|-ro|-r|-replication|-backup.*|.*-client)$")

ref_patterns = re.compile(
    r"(?:secretKeyRef|configMapRef|secretRef|configMap|claimName|persistentVolumeClaimName):\s*\n?\s*(?:name:\s*)?(\S+)"
)

problems = []
for doc in text.split("\n---\n"):
    if not re.search(r"helm\.sh/hook", doc):
        continue
    kind = re.search(r"^kind: (\w+)", doc, re.M)
    name = re.search(r"^  name: (\S+)", doc, re.M)
    if not kind or not name:
        continue
    self_ident = f"{kind.group(1)}/{name.group(1)}"
    for m in ref_patterns.finditer(doc):
        ref = m.group(1).strip('"')
        # Resolve templated names crudely: match against known resource names
        candidates = {p.split("/", 1)[1] for p in plain | hooks}
        matches = [c for c in candidates if c == ref or ref.endswith(c) or c.endswith(ref)]
        if not matches:
            continue  # external/operator-managed name we can't resolve — skip
        for c in matches:
            ident = next((p for p in plain | hooks if p.split("/", 1)[1] == c), None)
            if ident and ident in plain and ident != self_ident:
                if not OPERATOR_GENERATED.search(c):
                    problems.append(f"  hook {self_ident} references non-hook resource {ident}")
print("\n".join(sorted(set(problems))))
EOF
)

  if [[ -n "$violations" ]]; then
    echo "FAIL $name:"
    echo "$violations"
    fail=1
  else
    echo "OK   $name"
  fi

  rm -f "$rendered" "$hook_docs" "$plain_docs"
done

exit $fail
