#!/usr/bin/env bash
# Fails if any Helm hook template references a resource that is NOT itself a
# hook (or generated by an operator at runtime). This is the bug class that
# broke fresh eneo installs in 1.0.151–1.0.183: the pre-install migrate job
# mounted the eneo-files ConfigMap, but hooks run BEFORE regular manifests,
# so the mount 404'd on any fresh install.
#
# Usage: ./scripts/check-hook-deps.sh [chart-dir]...
# Exits non-zero if any chart has a violation.

set -uo pipefail

charts=("$@")
if [[ ${#charts[@]} -eq 0 ]]; then
  charts=(charts/*)
fi

fail=0

for chart in "${charts[@]}"; do
  [[ -d "$chart/templates" ]] || continue
  name=$(basename "$chart")

  rendered=$(mktemp)
  if ! helm template "$chart" --set global.domain=hookcheck.invalid >"$rendered" 2>"$rendered.err"; then
    echo "SKIP $name: helm template failed: $(head -1 "$rendered.err")"
    rm -f "$rendered" "$rendered.err"
    continue
  fi
  rm -f "$rendered.err"

  # One python pass: classify docs as hook/plain, then flag every resource
  # referenced FROM a hook that only exists as a plain manifest.
  report=$(python3 - "$rendered" <<'PYEOF'
import re, sys

text = open(sys.argv[1]).read()
docs = [d for d in text.split("\n---\n") if d.strip()]

def ident_of(doc):
    kind = re.search(r"^kind: (\w+)", doc, re.M)
    name = re.search(r"^  name: (\S+)", doc, re.M)
    return f"{kind.group(1)}/{name.group(1)}" if kind and name else None

hooks = {ident_of(d) for d in docs if re.search(r"helm\.sh/hook", d)} - {None}
plain = {ident_of(d) for d in docs if not re.search(r"helm\.sh/hook", d)} - {None}

# Resources generated by operators at runtime (CNPG etc.), not by the chart —
# they cannot be hooks, so referencing them from a hook is expected.
OPERATOR_GENERATED = re.compile(
    r"-(postgres-app|postgres-superuser|superuser|-rw|-ro|-r|replication|client)$"
)

# Resource names a manifest can reference.
REF = re.compile(
    r"(?:secretKeyRef|configMapRef|secretRef|configMap|claimName|"
    r"persistentVolumeClaimName|barmanObjectName):\s*\n?\s*(?:name:\s*)?(\S+)"
)

problems = []
for doc in docs:
    if not re.search(r"helm\.sh/hook", doc):
        continue
    self_ident = ident_of(doc)
    for m in REF.finditer(doc):
        ref = m.group(1).strip('"').rstrip("/")
        for ident in plain:
            res_name = ident.split("/", 1)[1]
            if (ref == res_name or ref.endswith(res_name)) and ident != self_ident \
               and not OPERATOR_GENERATED.search(res_name):
                problems.append(f"  hook {self_ident} references non-hook resource {ident}")

if problems:
    print("\n".join(sorted(set(problems))))
    sys.exit(1)
PYEOF
)
  status=$?

  if [[ $status -ne 0 ]]; then
    echo "FAIL $name:"
    echo "$report"
    fail=1
  else
    echo "OK   $name"
  fi

  rm -f "$rendered"
done

exit $fail
